names = ['Rohin Sood', 'Rohin Sood', 'Rohin Sood', 'Rohin Sood']
links = ['https://www.linkedin.com/in/rohin-sood-a51b4a218?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAADb8kV0BfI_be53aB3TNpmVcc38laksTV84', 'https://www.linkedin.com/in/rohinsood?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAAVvyHABKym_76_TJ8rMoibC2lhMn9uoI4M', 'https://www.linkedin.com/in/rohin-sood-8435156?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAAEk03MB0d2BwopaLlqJ2Q36ZQsfqFBMJQ0', 'https://www.linkedin.com/in/rohin-sood-08045b212?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAADXQ76AB7PD6aiwjcquGYFuCAOWfr0qTB0w']
currentCo = ["No Info Found for: Current Company", 'CLARA analytics', 'Samsung India Full-time', 'Amazon Full-time']
locations = ['San Diego, California, United States', 'San Francisco, California, United States', 'Kolkata, West Bengal, India', 'Weston-on-Trent, England, United Kingdom']
currentPos = ['--', 'Product Manager | Self-Starter | Builder', 'Senior manager at Samsung India', 'Currently studying at Trent College, applying to the degree Philosophy, Politics and Economics. Hoping to expand my knowledge and foundation in these areas through effective networking.'] 
experience = [[['No Info Found for: Title of Experience', 'No Info Found for: Company of Experience', 'No Info Found for: Duration of Experience', 'No Info Found for: URL for Experience']], [['Senior Product Manager', 'CLARA analytics', '2 yrs 6 mos', 'https://www.linkedin.comhttps://www.linkedin.com/company/clara-analytics/'], ['Product Manager', 'Autodesk', '2 yrs 9 mos', 'https://www.linkedin.comhttps://www.linkedin.com/company/autodesk/'], ['Product/Internal Strategy Intern – Customer Experience', 'Verizon Wireless', '2 mos', 'https://www.linkedin.comhttps://www.linkedin.com/company/verizon/'], ['No Info Found for: Title of Experience', 'No Info Found for: Company of Experience', 'No Info Found for: Duration of Experience', 'No Info Found for: URL for Experience'], ['Global Controllership Intern', 'GE', '7 mos', 'https://www.linkedin.comhttps://www.linkedin.com/company/ge/']], [['Sales And Marketing Specialist', 'Samsung India Full-time', '2 yrs 3 mos', 'https://www.linkedin.comhttps://www.linkedin.com/company/samsung-india/'], ['Deputy Manager', 'Reliance Digital Retail Ltd. Full-time', '11 yrs 5 mos', 'https://www.linkedin.comhttps://www.linkedin.com/company/reliance-digital-retail-ltd-/']], [['Warehouse Operations Specialist', 'Amazon Full-time', '6 mos', 'https://www.linkedin.comhttps://www.linkedin.com/company/amazon/']]]
education = [[['Del Norte High School', 'No Info Found for: Education Degree', 'No Info Found for: Duration of Education', 'https://www.linkedin.comhttps://www.linkedin.com/school/3195732/?legacySchoolId=3195732']], [['Cornell University - Johnson Graduate School of Management', 'Master of Business Administration (M.B.A.)', 'No Info Found for: Duration of Education', 'https://www.linkedin.comhttps://www.linkedin.com/school/18947/?legacySchoolId=18947'], ['Penn State University', 'Finance', 'No Info Found for: Duration of Education', 'https://www.linkedin.comhttps://www.linkedin.com/school/19318/?legacySchoolId=19318']], [['Indian Institute of Planning and Management', 'mba', 'No Info Found for: Duration of Education', 'https://www.linkedin.comhttps://www.linkedin.com/school/20940/?legacySchoolId=20940'], ['Punjab Technical University', 'Bachelor of Technology (B.Tech.)', 'No Info Found for: Duration of Education', 'https://www.linkedin.comhttps://www.linkedin.com/school/13596/?legacySchoolId=13596']], [['Trent College', 'No Info Found for: Education Degree', 'No Info Found for: Duration of Education', 'https://www.linkedin.comhttps://www.linkedin.com/school/5064002/?legacySchoolId=5064002']]]
searchString = "Rohin Sood"
searchURL = "https://www.linkedin.com/search/results/people/?keywords=Rohin%20Sood"
profileCount = 4
